name: ci
on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 'lts/*'

      - name: Install Node.js dependencies
        run: npm install --ignore-scripts --include=dev

      - name: Lint code
        run: npm run lint

  test:
    name: Test - Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.0.0, 18, 19, 20, 21, 22, 23, 24, 25]

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Install Node.js dependencies
        run: npm install

      - name: Run tests
        run: npm run test-ci

  pack:
    name: Pack npm tarball
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 23

      - name: Pack
        run: npm pack

      - name: Upload package tarball
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: npm-tarball
          path: ./body-parser-*.tgz
          if-no-files-found: error
